# -*- coding: utf-8 -*-
"""Ericsson_AI_ML_AUTOMATION_COURSE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChmpLXitX4paXkQO0YyJrgiq0hOlUEP0
"""

from sklearn.datasets import make_regression,make_classification

X,y = make_regression()

from sklearn import dummy

fakeestimator = dummy.DummyRegressor(strategy='median')

fakeestimator.fit(X,y)

fakeestimator.predict(X)[:5]

